language: csharp
install:
  - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
script:
  - mkdir build
  - bash update.sh
  - mono nuget.exe pack ./build/Paulovich.Caju.nuspec
  - mono nuget.exe setApiKey $NUGET_API_KEY -Source $NUGET_SOURCE
  - mono nuget.exe push Paulovich.Caju.*.nupkg -Source $NUGET_SOURCE